//! Generation of `flake.nix` from the workspace model, dependency graph, and
//! resolved lock.
//!
//! The generated flake:
//! - pins `nixpkgs` (and any overlay sources) to the immutable refs recorded in
//!   `granit.lock`;
//! - composes user overlays in declared order, then a Granit-generated
//!   workspace overlay that adds every package under `granitPackages`;
//! - defines each package as a `stdenv.mkDerivation` whose build script:
//!     1. materializes dependency outputs under `$GRANIT_DEPENDENCIES/<pkg>/<label>`,
//!     2. runs the user's command in a working directory,
//!     3. collects each declared `[outputs]` file into `$out/<label>`.
//!
//! Overlay/name precedence: nixpkgs -> user overlays (in listed order) ->
//! workspace overlay (added last, so workspace packages can shadow).

use crate::graph::Graph;
use crate::lock::Lock;
use crate::nixwriter::{self, NixWriter};
use crate::workspace::{Package, Workspace};

/// Which command a generated derivation runs. Defaults to `build`.
pub fn command_for<'a>(package: &'a Package, command: &str) -> Option<&'a str> {
    package.commands.get(command).map(|s| s.as_str())
}

/// Compute the path from `consumer`'s package dir to `producer_name`'s package
/// dir, relative to the consumer (e.g. `../common`). Used to mount a source
/// dependency at the sibling location the repo layout implies, so the
/// consumer's language tooling resolves it by path exactly as in the real tree.
///
/// Falls back to `../<producer>` if either dir can't be made relative.
fn sibling_rel_path(workspace: &Workspace, consumer: &Package, producer_name: &str) -> String {
    let producer_dir = match workspace.package(producer_name) {
        Some(p) => &p.dir,
        None => return format!("../{producer_name}"),
    };
    let rel = pathdiff_rel(&consumer.dir, producer_dir)
        .unwrap_or_else(|| format!("../{producer_name}"));
    rel
}

/// Minimal relative-path computation from `from` to `to` (both absolute or both
/// under the same root). Returns `None` if it can't be computed.
fn pathdiff_rel(from: &std::path::Path, to: &std::path::Path) -> Option<String> {
    use std::path::Component;
    let from_comps: Vec<Component> = from.components().collect();
    let to_comps: Vec<Component> = to.components().collect();
    // Find common prefix length.
    let mut i = 0;
    while i < from_comps.len() && i < to_comps.len() && from_comps[i] == to_comps[i] {
        i += 1;
    }
    let ups = from_comps.len() - i;
    let mut parts: Vec<String> = Vec::new();
    for _ in 0..ups {
        parts.push("..".to_string());
    }
    for c in &to_comps[i..] {
        parts.push(c.as_os_str().to_string_lossy().replace('\\', "/"));
    }
    if parts.is_empty() {
        Some(".".to_string())
    } else {
        Some(parts.join("/"))
    }
}

/// Generate the full `flake.nix` text for a workspace, targeting exactly
/// `system` (e.g. `aarch64-darwin`).
///
/// `command` selects which named command each derivation runs (e.g. `build`).
pub fn generate(
    workspace: &Workspace,
    graph: &Graph,
    lock: &Lock,
    command: &str,
    targets: &[String],
    system: &str,
) -> anyhow::Result<String> {
    let mut w = NixWriter::new();

    w.line("# Generated by granit. Do not edit by hand.");
    w.line("# Regenerate with `granit build` (pins come from granit.lock).");
    w.line("{");
    w.indented(|w| {
        w.assign_string("description", "granit-generated workspace flake");
        w.blank();

        // ---- inputs ----
        w.line("inputs = {");
        w.indented(|w| {
            w.assign_url("nixpkgs", &lock.nixpkgs.locked_ref);
            for (i, overlay) in lock.overlays.iter().enumerate() {
                w.assign_url(&format!("granitOverlay{i}"), &overlay.locked_ref);
            }
        });
        w.line("};");
        w.blank();

        // ---- outputs ----
        let mut args = vec!["self".to_string(), "nixpkgs".to_string()];
        for i in 0..lock.overlays.len() {
            args.push(format!("granitOverlay{i}"));
        }
        w.line(&format!("outputs = {{ {} }}:", args.join(", ")));
        w.indented(|w| {
            w.line("let");
            w.indented(|w| emit_let_bindings(w, workspace, graph, command, targets, lock.overlays.len(), system));
            w.line("in {");
            w.indented(|w| {
                emit_packages_output(w, graph, system);
                emit_devshells_output(w, workspace, graph, system);
            });
            w.line("};");
        });
    });
    w.line("}");

    Ok(w.build())
}

/// Emit the `let` bindings: overlays, workspaceOverlay, and `pkgs` for the
/// target system.
fn emit_let_bindings(
    w: &mut NixWriter,
    workspace: &Workspace,
    graph: &Graph,
    command: &str,
    targets: &[String],
    overlay_count: usize,
    system: &str,
) {
    // User overlays, composed in declared order.
    w.line("userOverlays = [");
    w.indented(|w| {
        for i in 0..overlay_count {
            w.line(&format!(
                "(granitOverlay{i}.overlays.default or (final: prev: {{}}))"
            ));
        }
    });
    w.line("];");

    // The workspace overlay adds each package under `granitPackages`.
    w.line("workspaceOverlay = final: prev: {");
    w.indented(|w| {
        w.line("granitPackages =");
        w.indented(|w| {
            w.line("let");
            w.indented(|w| w.line("gp = final.granitPackages;"));
            w.line("in {");
            w.indented(|w| {
                for name in &graph.order {
                    let pkg = workspace
                        .package(name)
                        .expect("graph order references a known package");
                    // The requested command applies only to the target
                    // package(s) named on the command line; their dependencies
                    // are always *built* (their `build` command) so their
                    // declared outputs exist for the target to consume via
                    // $GRANIT_DEPENDENCIES. Otherwise a `granit run <cmd>` would
                    // try to run <cmd> on dependencies that don't define it.
                    let pkg_command = if targets.iter().any(|t| t == name) {
                        command
                    } else {
                        "build"
                    };
                    // Emit `<attr> = <derivation>;` where the derivation is a
                    // multi-line block; open the assignment then render the body.
                    w.line(&format!("{} = final.stdenv.mkDerivation {{", nixwriter::attr(name)));
                    w.indented(|w| emit_derivation_body(w, workspace, pkg, pkg_command, &workspace.root));
                    w.line("};");
                }
            });
            w.line("};");
        });
    });
    w.line("};");

    // Import nixpkgs for exactly the target system with all overlays applied.
    w.line(&format!("pkgs = import nixpkgs {{"));
    w.indented(|w| {
        w.assign_string("system", system);
        w.line("overlays = userOverlays ++ [ workspaceOverlay ];");
    });
    w.line("};");
}

/// Emit the `packages.<system>` output attribute.
fn emit_packages_output(w: &mut NixWriter, graph: &Graph, system: &str) {
    w.line(&format!("packages.{} = {{", nixwriter::attr(system)));
    w.indented(|w| {
        for name in &graph.order {
            let a = nixwriter::attr(name);
            w.line(&format!("{a} = pkgs.granitPackages.{a};"));
        }
    });
    w.line("};");
}

/// Emit the `devShells.<system>` output attribute: one shell per package that
/// puts the package's `tools` on `PATH` and materializes its dependency outputs
/// under `$GRANIT_DEPENDENCIES`. This backs *custom* commands (`granit run
/// <cmd>`), which run in the user's real source directory (not a sandbox) so
/// tasks like `go generate` can write back into the tree.
fn emit_devshells_output(
    w: &mut NixWriter,
    workspace: &Workspace,
    graph: &Graph,
    system: &str,
) {
    w.line(&format!("devShells.{} = {{", nixwriter::attr(system)));
    w.indented(|w| {
        for name in &graph.order {
            let pkg = workspace
                .package(name)
                .expect("graph order references a known package");
            let a = nixwriter::attr(name);
            w.line(&format!("{a} = pkgs.mkShell {{"));
            w.indented(|w| {
                // Tools on PATH (resolved against the merged package set).
                let tools: String = pkg
                    .tools
                    .iter()
                    .map(|t| format!("pkgs.{} ", nixwriter::attr(t)))
                    .collect();
                w.assign("packages", &format!("[ {tools}]"));

                // Artifact dependency derivations, so Nix builds them before the
                // shell starts and we can materialize their outputs. Source
                // dependencies are NOT materialized here: dev commands run in
                // the real source tree, where the sibling package already
                // exists at its repo-relative path.
                let artifact_deps: Vec<&crate::workspace::DependencyRef> = pkg
                    .dependencies
                    .iter()
                    .filter(|dep| {
                        !workspace
                            .package(&dep.package)
                            .and_then(|p| p.outputs.get(&dep.label))
                            .map(|o| o.is_source)
                            .unwrap_or(false)
                    })
                    .collect();
                if !artifact_deps.is_empty() {
                    w.line("granitDeps = [");
                    w.indented(|w| {
                        for dep in &artifact_deps {
                            w.line(&format!(
                                "\"{}:{}:${{pkgs.granitPackages.{}}}\"",
                                nixwriter::escape_nix_dq(&dep.package),
                                nixwriter::escape_nix_dq(&dep.label),
                                nixwriter::attr(&dep.package)
                            ));
                        }
                    });
                    w.line("];");
                }

                // shellHook materializes artifact dependency outputs into a
                // fresh temp dir and exports GRANIT_DEPENDENCIES to it. Custom
                // commands run via `nix develop --command`, inheriting this env.
                w.line("shellHook = ''");
                w.indented(|w| {
                    w.line("export GRANIT_DEPENDENCIES=\"$(mktemp -d)/granit-deps\"");
                    w.line("mkdir -p \"$GRANIT_DEPENDENCIES\"");
                    if !artifact_deps.is_empty() {
                        w.line("for entry in $granitDeps; do");
                        w.indented(|w| {
                            w.line("depPkg=\"''${entry%%:*}\"");
                            w.line("rest=\"''${entry#*:}\"");
                            w.line("depLabel=\"''${rest%%:*}\"");
                            w.line("depPath=\"''${rest#*:}\"");
                            w.line("mkdir -p \"$GRANIT_DEPENDENCIES/$depPkg\"");
                            w.line("cp -rL \"$depPath/$depLabel\" \"$GRANIT_DEPENDENCIES/$depPkg/$depLabel\"");
                        });
                        w.line("done");
                    }
                });
                w.line("'';");
            });
            w.line("};");
        }
    });
    w.line("};");
}

/// Emit the body of a package's `stdenv.mkDerivation { ... }` (the caller has
/// already written the opening `mkDerivation {` line).
fn emit_derivation_body(
    w: &mut NixWriter,
    workspace: &Workspace,
    pkg: &Package,
    command: &str,
    root: &std::path::Path,
) {
    w.assign_string("pname", &pkg.name);
    w.assign_string("version", "0.0.0");

    // src: the package's own files, filtered by the computed include set. Nix's
    // default unpackPhase copies this into the (writable) build dir, so the user
    // command runs against the package's real source (package.json, etc.).
    emit_src(w, pkg, root);

    // buildInputs from tools (resolved against the merged package set `final`).
    let inputs: String = pkg
        .tools
        .iter()
        .map(|t| format!("final.{} ", nixwriter::attr(t)))
        .collect();
    w.assign("buildInputs", &format!("[ {inputs}]"));

    // Split dependencies into artifact deps (materialized under
    // $GRANIT_DEPENDENCIES) and source deps (mounted repo-relative as sibling
    // source trees, so the consumer's language tooling resolves them by path).
    let mut artifact_deps: Vec<&crate::workspace::DependencyRef> = Vec::new();
    let mut source_deps: Vec<(&crate::workspace::DependencyRef, String)> = Vec::new();
    for dep in &pkg.dependencies {
        let is_source = workspace
            .package(&dep.package)
            .and_then(|p| p.outputs.get(&dep.label))
            .map(|o| o.is_source)
            .unwrap_or(false);
        if is_source {
            // Path from the consumer's package dir to the producer's package
            // dir (e.g. `../common`), so the mounted tree preserves the repo
            // layout the language tool expects.
            let target = sibling_rel_path(workspace, pkg, &dep.package);
            source_deps.push((dep, target));
        } else {
            artifact_deps.push(dep);
        }
    }

    // Pass artifact dependency derivations so Nix wires build order and paths.
    if !artifact_deps.is_empty() {
        w.line("granitDeps = [");
        w.indented(|w| {
            for dep in &artifact_deps {
                // Entry format "pkg:label:<storePath>"; ${gp.<pkg>} is intended
                // Nix interpolation of the dependency's out path.
                w.line(&format!(
                    "\"{}:{}:${{gp.{}}}\"",
                    nixwriter::escape_nix_dq(&dep.package),
                    nixwriter::escape_nix_dq(&dep.label),
                    nixwriter::attr(&dep.package)
                ));
            }
        });
        w.line("];");
    }

    // Pass source dependency derivations; each entry carries the producer's
    // collected source path and the sibling location to mount it at.
    if !source_deps.is_empty() {
        w.line("granitSourceDeps = [");
        w.indented(|w| {
            for (dep, target) in &source_deps {
                // Entry format "<targetRelPath>:<storePath>/<label>".
                w.line(&format!(
                    "\"{}:${{gp.{}}}/{}\"",
                    nixwriter::escape_nix_dq(target),
                    nixwriter::attr(&dep.package),
                    nixwriter::escape_nix_dq(&dep.label)
                ));
            }
        });
        w.line("];");
    }

    let user_cmd = command_for(pkg, command).unwrap_or("");

    // buildPhase runs in $PWD, which stdenv has populated with the unpacked
    // (writable) source. GRANIT_DEPENDENCIES is materialized under
    // $NIX_BUILD_TOP so dependency outputs are available to the command.
    w.line("buildPhase = ''");
    w.indented(|w| {
        w.line("runHook preBuild");
        w.line("set -euo pipefail");
        // Nix sets $HOME to the non-writable placeholder /homeless-shelter.
        // Many tools (npm, pip, cargo, gradle) write caches/logs under $HOME
        // and crash. Give the build a writable HOME under the build dir.
        w.line("export HOME=\"$NIX_BUILD_TOP/granit-home\"");
        w.line("export XDG_CACHE_HOME=\"$HOME/.cache\"");
        w.line("mkdir -p \"$HOME\" \"$XDG_CACHE_HOME\"");
        // Builds run without a TTY. Signal non-interactive/no-progress mode so
        // tools (npm, yarn, ...) don't hang or crash on progress spinners.
        w.line("export CI=\"true\"");
        w.line("export TERM=\"dumb\"");
        w.line("export GRANIT_DEPENDENCIES=\"$NIX_BUILD_TOP/granit-deps\"");
        w.line("mkdir -p \"$GRANIT_DEPENDENCIES\"");
        if !artifact_deps.is_empty() {
            // `''${...}` escapes Nix interpolation so the shell sees `${...}`.
            w.line("for entry in $granitDeps; do");
            w.indented(|w| {
                w.line("depPkg=\"''${entry%%:*}\"");
                w.line("rest=\"''${entry#*:}\"");
                w.line("depLabel=\"''${rest%%:*}\"");
                w.line("depPath=\"''${rest#*:}\"");
                w.line("mkdir -p \"$GRANIT_DEPENDENCIES/$depPkg\"");
                w.line("cp -rL \"$depPath/$depLabel\" \"$GRANIT_DEPENDENCIES/$depPkg/$depLabel\"");
            });
            w.line("done");
        }
        if !source_deps.is_empty() {
            // Mount each source dependency's tree at its repo-relative sibling
            // location so the language's own path-based resolution finds it
            // (e.g. a Go/Rust/Node `replace`/path dependency on `../common`).
            w.line("for entry in $granitSourceDeps; do");
            w.indented(|w| {
                w.line("srcTarget=\"''${entry%%:*}\"");
                w.line("srcPath=\"''${entry#*:}\"");
                w.line("mkdir -p \"$(dirname \"$srcTarget\")\"");
                // Copy writable so tooling (e.g. codegen) can operate if needed.
                w.line("cp -rL \"$srcPath\" \"$srcTarget\"");
                w.line("chmod -R u+w \"$srcTarget\"");
            });
            w.line("done");
        }
        w.line("# --- user command ---");
        for line in user_cmd.lines() {
            w.line(&nixwriter::escape_nix_multiline(line));
        }
        w.line("# --- end user command ---");
        w.line("runHook postBuild");
    });
    w.line("'';");

    // installPhase runs in the same $PWD; collect declared outputs into
    // $out/<label> (produced by the build command in the source dir).
    w.line("installPhase = ''");
    w.indented(|w| {
        w.line("runHook preInstall");
        w.line("set -euo pipefail");
        w.line("mkdir -p \"$out\"");
        for (label, output) in &pkg.outputs {
            // Both artifact and source outputs are collected into $out/<label>.
            // For a source output, `output.path` is typically "." (the whole
            // unpacked source tree); consumers mount it repo-relative rather
            // than reading it from $GRANIT_DEPENDENCIES.
            w.line(&format!(
                "cp -rL {} \"$out/{}\"",
                nixwriter::shell_single_quote(&output.path),
                nixwriter::escape_nix_multiline(label)
            ));
        }
        w.line("runHook postInstall");
    });
    w.line("'';");
}

/// Emit the `src = builtins.path { ... };` attribute with a filter that keeps
/// exactly the package's included files (and their ancestor directories).
///
/// The path is expressed *relative to the flake root* (the workspace root),
/// so it resolves inside the flake's own store copy under pure evaluation.
/// The include set is computed in Rust (gitignore-style excludes) and embedded
/// as a Nix attrset used for O(1) membership checks in the filter.
fn emit_src(w: &mut NixWriter, pkg: &Package, root: &std::path::Path) {
    let included = crate::source::included_files(&pkg.dir, &pkg.exclude).unwrap_or_default();

    // Path to the package dir relative to the flake root (e.g. `packages/a`).
    let rel_dir = pkg
        .dir
        .strip_prefix(root)
        .unwrap_or(&pkg.dir)
        .to_string_lossy()
        .replace('\\', "/");
    // A relative Nix path literal resolves within the flake root in pure mode.
    let nix_path = format!("./{rel_dir}");

    // Build the allow-set: every included file plus all of its ancestor dirs
    // (relative to the package root), so the filter keeps the directories that
    // lead to included files.
    let mut allow: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for file in &included {
        let rel = file.to_string_lossy().replace('\\', "/");
        let mut acc = String::new();
        for seg in rel.split('/') {
            if !acc.is_empty() {
                acc.push('/');
            }
            acc.push_str(seg);
            allow.insert(acc.clone());
        }
    }

    w.line("src = builtins.path {");
    w.indented(|w| {
        w.assign_string("name", &format!("{}-src", pkg.name));
        w.line(&format!("path = {nix_path};"));
        // The filter receives paths under the source root; compute the path
        // relative to the root and keep it iff it's in the allow-set.
        w.line("filter = path: type:");
        w.indented(|w| {
            w.line("let");
            w.indented(|w| {
                w.line(&format!("rootStr = toString {nix_path};"));
                w.line("full = toString path;");
                // builtins.path only ever passes paths at or under the root, so
                // stripping "rootStr/" yields the package-relative path. The root
                // itself (full == rootStr) is always kept.
                w.line("rel = builtins.substring (builtins.stringLength rootStr + 1) (builtins.stringLength full) full;");
                w.line("allow = {");
                w.indented(|w| {
                    for p in &allow {
                        w.line(&format!("{} = true;", nixwriter::attr(p)));
                    }
                });
                w.line("};");
            });
            w.line("in full == rootStr || (allow ? ${rel});");
        });
    });
    w.line("};");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph;
    use crate::lock::{Lock, LockedInput};
    use crate::workspace::{DependencyRef, Package, Workspace};
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    fn pkg(
        name: &str,
        tools: &[&str],
        deps: &[(&str, &str)],
        outputs: &[(&str, &str)],
        build: &str,
    ) -> Package {
        let mut cmds = BTreeMap::new();
        cmds.insert("build".to_string(), build.to_string());
        Package {
            name: name.to_string(),
            dir: PathBuf::from(name),
            tools: tools.iter().map(|s| s.to_string()).collect(),
            dependencies: deps
                .iter()
                .map(|(p, l)| DependencyRef {
                    package: p.to_string(),
                    label: l.to_string(),
                })
                .collect(),
            exclude: vec![],
            outputs: outputs
                .iter()
                .map(|(l, f)| {
                    (
                        l.to_string(),
                        crate::workspace::Output {
                            path: f.to_string(),
                            is_source: false,
                        },
                    )
                })
                .collect(),
            commands: cmds,
        }
    }

    fn two_package_ws() -> Workspace {
        Workspace {
            name: "example".into(),
            root: PathBuf::from("/tmp/example"),
            nixpkgs_ref: "github:NixOS/nixpkgs/nixpkgs-unstable".into(),
            overlays: vec![],
            packages: vec![
                pkg(
                    "a",
                    &["coreutils"],
                    &[],
                    &[("hello", "hello.txt")],
                    "echo 'hello world' > hello.txt",
                ),
                pkg(
                    "b",
                    &["coreutils"],
                    &[("a", "hello")],
                    &[("result", "from-a.txt")],
                    "cat $GRANIT_DEPENDENCIES/a/hello > from-a.txt",
                ),
            ],
        }
    }

    fn lock_for(nixpkgs_rev: &str, overlays: Vec<LockedInput>) -> Lock {
        Lock {
            version: Lock::CURRENT_VERSION,
            nixpkgs: LockedInput {
                original_ref: "github:NixOS/nixpkgs/nixpkgs-unstable".into(),
                locked_ref: format!("github:NixOS/nixpkgs/{nixpkgs_rev}"),
                rev: Some(nixpkgs_rev.into()),
                nar_hash: Some("sha256-x=".into()),
                last_modified: Some(1),
            },
            overlays,
        }
    }

    #[test]
    fn generates_pinned_nixpkgs_input() {
        let ws = two_package_ws();
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("deadbeefdeadbeef", vec![]);
        let nix = generate(&ws, &g, &lock, "build", &[], "x86_64-linux").unwrap();
        assert!(
            nix.contains("nixpkgs.url = \"github:NixOS/nixpkgs/deadbeefdeadbeef\""),
            "missing pinned nixpkgs input:\n{nix}"
        );
        // Targets exactly the requested system, with no multi-system machinery.
        assert!(
            nix.contains("packages.x86_64-linux = {"),
            "should emit packages for the target system only:\n{nix}"
        );
        assert!(!nix.contains("forAllSystems"), "should not emit forAllSystems:\n{nix}");
    }

    #[test]
    fn generates_buildinputs_from_tools() {
        let ws = two_package_ws();
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);
        let nix = generate(&ws, &g, &lock, "build", &[], "x86_64-linux").unwrap();
        assert!(
            nix.contains("buildInputs = [ final.coreutils ];"),
            "missing buildInputs:\n{nix}"
        );
    }

    #[test]
    fn wires_dependency_outputs() {
        let ws = two_package_ws();
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);
        let nix = generate(&ws, &g, &lock, "build", &[], "x86_64-linux").unwrap();
        // b's derivation references a's store path via the overlay fixpoint.
        assert!(
            nix.contains("\"a:hello:${gp.a}\""),
            "missing dependency wiring:\n{nix}"
        );
        // The build script populates $GRANIT_DEPENDENCIES.
        assert!(nix.contains("$GRANIT_DEPENDENCIES/$depPkg/$depLabel"));
        // Shell parameter expansions in the boilerplate must be escaped so Nix
        // does not try to interpolate them.
        assert!(
            nix.contains("''${entry%%:*}"),
            "boilerplate shell expansion not escaped:\n{nix}"
        );
    }

    #[test]
    fn custom_command_applies_only_to_target_deps_run_build() {
        // Workspace: b depends on a. Only b is the target. Requesting a command
        // that a does not define ("test") must NOT blank out a's build script:
        // dependencies always run their `build` command so their outputs exist
        // for the target to consume via $GRANIT_DEPENDENCIES.
        let ws = two_package_ws();
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);

        let nix = generate(&ws, &g, &lock, "test", &["b".to_string()], "x86_64-linux").unwrap();

        // a's actual build command must be present (a ran `build`, not `test`).
        // The buildPhase user command is command-specific; output collection is
        // not, so we assert on the command body itself.
        assert!(
            nix.contains("echo 'hello world' > hello.txt"),
            "dependency `a` should run its build command, not the (missing) target command:\n{nix}"
        );
    }

    #[test]
    fn emits_devshells_with_tools_and_dep_materialization() {
        let ws = two_package_ws();
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);
        let nix = generate(&ws, &g, &lock, "build", &[], "x86_64-linux").unwrap();

        // A devShells output exists for the target system.
        assert!(
            nix.contains("devShells.x86_64-linux = {"),
            "missing devShells output:\n{nix}"
        );
        // Each package gets a mkShell with its tools on PATH.
        assert!(nix.contains("pkgs.mkShell {"), "missing mkShell:\n{nix}");
        assert!(
            nix.contains("packages = [ pkgs.coreutils ];"),
            "devShell should put tools on PATH:\n{nix}"
        );
        // b's devShell materializes its dependency a:hello under
        // $GRANIT_DEPENDENCIES via the shellHook.
        assert!(
            nix.contains("\"a:hello:${pkgs.granitPackages.a}\""),
            "devShell should wire dependency outputs:\n{nix}"
        );
        assert!(
            nix.contains("export GRANIT_DEPENDENCIES="),
            "devShell shellHook should export GRANIT_DEPENDENCIES:\n{nix}"
        );
    }

    #[test]
    fn source_dependency_is_mounted_repo_relative_not_in_granit_deps() {
        // common exposes a `source` output; app depends on `common:src`.
        let common = pkg("common", &["go"], &[], &[("src", ".")], "go build ./...");
        // Mark common's `src` output as a source output.
        let mut common = common;
        common.outputs.get_mut("src").unwrap().is_source = true;

        let app = pkg(
            "app",
            &["go"],
            &[("common", "src")],
            &[],
            "go build ./...",
        );

        let ws = Workspace {
            name: "src-dep".into(),
            root: PathBuf::from("/tmp/wsroot"),
            nixpkgs_ref: "github:NixOS/nixpkgs/nixpkgs-unstable".into(),
            overlays: vec![],
            packages: vec![
                {
                    let mut c = common;
                    c.dir = PathBuf::from("/tmp/wsroot/packages/common");
                    c
                },
                {
                    let mut a = app;
                    a.dir = PathBuf::from("/tmp/wsroot/packages/app");
                    a
                },
            ],
        };
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);
        let nix = generate(&ws, &g, &lock, "build", &["app".to_string()], "x86_64-linux").unwrap();

        // app mounts common as a repo-relative sibling (../common), NOT via
        // $GRANIT_DEPENDENCIES.
        assert!(
            nix.contains("granitSourceDeps = ["),
            "expected a source-deps list:\n{nix}"
        );
        assert!(
            nix.contains("\"../common:${gp.common}/src\""),
            "source dep should mount at ../common from app:\n{nix}"
        );
        // common's source output is collected into $out/src so it can be mounted.
        assert!(
            nix.contains("cp -rL '.' \"$out/src\""),
            "common should collect its source tree into $out/src:\n{nix}"
        );
        // The source-dep mount loop is emitted.
        assert!(nix.contains("for entry in $granitSourceDeps; do"));
    }

    #[test]
    fn collects_declared_outputs() {
        let ws = two_package_ws();
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);
        let nix = generate(&ws, &g, &lock, "build", &[], "x86_64-linux").unwrap();
        // a collects hello.txt -> $out/hello
        assert!(
            nix.contains("cp -rL 'hello.txt' \"$out/hello\""),
            "missing output collection for a:\n{nix}"
        );
        // b collects from-a.txt -> $out/result
        assert!(nix.contains("cp -rL 'from-a.txt' \"$out/result\""));
    }

    #[test]
    fn composes_user_overlays_in_order() {
        let mut ws = two_package_ws();
        ws.overlays = vec![
            crate::workspace::Overlay {
                source: "github:acme/first".into(),
            },
            crate::workspace::Overlay {
                source: "github:acme/second".into(),
            },
        ];
        let g = graph::build(&ws).unwrap();
        let lock = lock_for(
            "rev",
            vec![
                LockedInput {
                    original_ref: "github:acme/first".into(),
                    locked_ref: "github:acme/first/1111".into(),
                    rev: Some("1111".into()),
                    nar_hash: None,
                    last_modified: None,
                },
                LockedInput {
                    original_ref: "github:acme/second".into(),
                    locked_ref: "github:acme/second/2222".into(),
                    rev: Some("2222".into()),
                    nar_hash: None,
                    last_modified: None,
                },
            ],
        );
        let nix = generate(&ws, &g, &lock, "build", &[], "x86_64-linux").unwrap();
        assert!(nix.contains("granitOverlay0.url = \"github:acme/first/1111\""));
        assert!(nix.contains("granitOverlay1.url = \"github:acme/second/2222\""));
        // Overlay 0 must appear before overlay 1 in the composed list.
        let idx0 = nix.find("granitOverlay0.overlays.default").unwrap();
        let idx1 = nix.find("granitOverlay1.overlays.default").unwrap();
        assert!(idx0 < idx1, "overlays not composed in declared order");
        // workspaceOverlay is applied after user overlays.
        assert!(nix.contains("userOverlays ++ [ workspaceOverlay ]"));
    }

    #[test]
    fn escapes_interpolation_in_user_commands() {
        // A user command containing `${FOO}` must reach the shell literally,
        // not be interpolated by Nix.
        let ws = Workspace {
            name: "x".into(),
            root: PathBuf::from("/tmp/x"),
            nixpkgs_ref: "github:NixOS/nixpkgs/nixpkgs-unstable".into(),
            overlays: vec![],
            packages: vec![pkg(
                "a",
                &[],
                &[],
                &[("o", "o.txt")],
                "echo ${HOME} > o.txt",
            )],
        };
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);
        let nix = generate(&ws, &g, &lock, "build", &[], "x86_64-linux").unwrap();
        assert!(
            nix.contains("echo ''${HOME} > o.txt"),
            "interpolation not escaped:\n{nix}"
        );
    }
}
