//! Generation of `flake.nix` from the workspace model, dependency graph, and
//! resolved lock.
//!
//! The generated flake:
//! - pins `nixpkgs` (and any overlay sources) to the immutable refs recorded in
//!   `granit.lock`;
//! - composes user overlays in declared order, then a Granit-generated
//!   workspace overlay that adds every package under `granitPackages`;
//! - defines each package as a `stdenv.mkDerivation` whose build script:
//!     1. materializes dependency outputs under `$GRANIT_DEPENDENCIES/<pkg>/<label>`,
//!     2. runs the user's command in a working directory,
//!     3. collects each declared `[outputs]` file into `$out/<label>`.
//!
//! Overlay/name precedence: nixpkgs -> user overlays (in listed order) ->
//! workspace overlay (added last, so workspace packages can shadow).

use crate::graph::Graph;
use crate::lock::Lock;
use crate::workspace::{Package, Workspace};

/// The systems the generated flake will expose packages for.
const SYSTEMS: &[&str] = &[
    "x86_64-linux",
    "aarch64-linux",
    "x86_64-darwin",
    "aarch64-darwin",
];

/// Which command a generated derivation runs. Defaults to `build`.
pub fn command_for<'a>(package: &'a Package, command: &str) -> Option<&'a str> {
    package.commands.get(command).map(|s| s.as_str())
}

/// Generate the full `flake.nix` text for a workspace.
///
/// `command` selects which named command each derivation runs (e.g. `build`).
pub fn generate(
    workspace: &Workspace,
    graph: &Graph,
    lock: &Lock,
    command: &str,
) -> anyhow::Result<String> {
    let mut out = String::new();

    out.push_str("# Generated by granit. Do not edit by hand.\n");
    out.push_str("# Regenerate with `granit build` (pins come from granit.lock).\n");
    out.push_str("{\n");
    out.push_str("  description = \"granit-generated workspace flake\";\n\n");

    // ---- inputs ----
    out.push_str("  inputs = {\n");
    out.push_str(&format!(
        "    nixpkgs.url = {};\n",
        nix_string(&lock.nixpkgs.locked_ref)
    ));
    for (i, overlay) in lock.overlays.iter().enumerate() {
        out.push_str(&format!(
            "    granitOverlay{i}.url = {};\n",
            nix_string(&overlay.locked_ref)
        ));
    }
    out.push_str("  };\n\n");

    // ---- outputs ----
    // Argument list: self, nixpkgs, and each overlay input by name.
    let mut arg_names = vec!["self".to_string(), "nixpkgs".to_string()];
    for i in 0..lock.overlays.len() {
        arg_names.push(format!("granitOverlay{i}"));
    }
    out.push_str(&format!(
        "  outputs = {{ {} }}:\n",
        arg_names.join(", ")
    ));
    out.push_str("    let\n");
    out.push_str(&format!("      systems = [ {} ];\n", systems_list()));
    out.push_str(
        "      forAllSystems = f: nixpkgs.lib.genAttrs systems (system: f system);\n",
    );

    // User overlays: each input is expected to expose `overlays.default`.
    // Compose them in declared order.
    out.push_str("      userOverlays = [\n");
    for i in 0..lock.overlays.len() {
        out.push_str(&format!(
            "        (granitOverlay{i}.overlays.default or (final: prev: {{}}))\n"
        ));
    }
    out.push_str("      ];\n");

    // The workspace overlay adds each package under `granitPackages`.
    out.push_str("      workspaceOverlay = final: prev: {\n");
    out.push_str("        granitPackages =\n");
    out.push_str("          let\n");
    out.push_str("            gp = final.granitPackages;\n");
    out.push_str("          in {\n");

    // Emit each package derivation in topological order.
    for name in &graph.order {
        let pkg = workspace
            .package(name)
            .expect("graph order references a known package");
        let drv = render_package_derivation(pkg, command);
        // Indent the derivation under the attribute.
        out.push_str(&format!("            {} = {};\n", nix_attr(name), drv));
    }

    out.push_str("          };\n");
    out.push_str("      };\n");

    // Build pkgs per system with all overlays applied.
    out.push_str("      pkgsFor = system: import nixpkgs {\n");
    out.push_str("        inherit system;\n");
    out.push_str("        overlays = userOverlays ++ [ workspaceOverlay ];\n");
    out.push_str("      };\n");
    out.push_str("    in {\n");
    out.push_str("      packages = forAllSystems (system:\n");
    out.push_str("        let pkgs = pkgsFor system; in {\n");
    for name in &graph.order {
        out.push_str(&format!(
            "          {} = pkgs.granitPackages.{};\n",
            nix_attr(name),
            nix_attr(name)
        ));
    }
    out.push_str("        });\n");
    out.push_str("    };\n");
    out.push_str("}\n");

    Ok(out)
}

/// Render a single package as a `stdenv.mkDerivation` expression.
///
/// Uses the overlay fixpoint (`gp = final.granitPackages`) so dependencies
/// reference sibling derivations by `gp.<dep>`.
fn render_package_derivation(pkg: &Package, command: &str) -> String {
    let mut s = String::new();
    s.push_str("final.stdenv.mkDerivation {\n");
    s.push_str(&format!("              pname = {};\n", nix_string(&pkg.name)));
    s.push_str("              version = \"0.0.0\";\n");
    s.push_str("              dontUnpack = true;\n");

    // buildInputs from tools (resolved against the merged package set `final`).
    s.push_str("              buildInputs = [ ");
    for tool in &pkg.tools {
        s.push_str(&format!("final.{} ", nix_attr(tool)));
    }
    s.push_str("];\n");

    // Pass dependency derivations so Nix wires the build order and store paths.
    // We expose them to the builder via an environment array.
    if !pkg.dependencies.is_empty() {
        s.push_str("              granitDeps = [\n");
        for dep in &pkg.dependencies {
            // Each entry is "pkg:label:<storePath-of-dep>".
            s.push_str(&format!(
                "                \"{}:{}:${{gp.{}}}\"\n",
                escape_nix_dq(&dep.package),
                escape_nix_dq(&dep.label),
                nix_attr(&dep.package)
            ));
        }
        s.push_str("              ];\n");
    }

    let user_cmd = command_for(pkg, command).unwrap_or("");

    // The build script: wire dependencies, run the user command, collect outputs.
    // GRANIT_WORK and GRANIT_DEPENDENCIES live under $NIX_BUILD_TOP so that they
    // persist between the buildPhase and installPhase (which run as separate
    // shell invocations within the same derivation build).
    s.push_str("              buildPhase = ''\n");
    s.push_str("                runHook preBuild\n");
    s.push_str("                set -euo pipefail\n");
    s.push_str("                export GRANIT_WORK=\"$NIX_BUILD_TOP/granit-work\"\n");
    s.push_str("                export GRANIT_DEPENDENCIES=\"$NIX_BUILD_TOP/granit-deps\"\n");
    s.push_str("                mkdir -p \"$GRANIT_WORK\" \"$GRANIT_DEPENDENCIES\"\n");
    // Materialize each dependency output at $GRANIT_DEPENDENCIES/<pkg>/<label>.
    // Note: `''${...}` escapes Nix interpolation so the shell sees `${...}`.
    if !pkg.dependencies.is_empty() {
        s.push_str("                for entry in $granitDeps; do\n");
        s.push_str("                  depPkg=\"''${entry%%:*}\"\n");
        s.push_str("                  rest=\"''${entry#*:}\"\n");
        s.push_str("                  depLabel=\"''${rest%%:*}\"\n");
        s.push_str("                  depPath=\"''${rest#*:}\"\n");
        s.push_str("                  mkdir -p \"$GRANIT_DEPENDENCIES/$depPkg\"\n");
        s.push_str(
            "                  cp -rL \"$depPath/$depLabel\" \"$GRANIT_DEPENDENCIES/$depPkg/$depLabel\"\n",
        );
        s.push_str("                done\n");
    }
    s.push_str("                cd \"$GRANIT_WORK\"\n");
    // Run the user command.
    s.push_str("                # --- user command ---\n");
    for line in user_cmd.lines() {
        s.push_str("                ");
        s.push_str(&escape_nix_multiline(line));
        s.push('\n');
    }
    s.push_str("                # --- end user command ---\n");
    s.push_str("                runHook postBuild\n");
    s.push_str("              '';\n");

    // Install phase: collect declared outputs into $out/<label>.
    s.push_str("              installPhase = ''\n");
    s.push_str("                runHook preInstall\n");
    s.push_str("                set -euo pipefail\n");
    s.push_str("                export GRANIT_WORK=\"$NIX_BUILD_TOP/granit-work\"\n");
    s.push_str("                mkdir -p \"$out\"\n");
    s.push_str("                cd \"$GRANIT_WORK\"\n");
    for (label, filename) in &pkg.outputs {
        s.push_str(&format!(
            "                cp -rL {} \"$out/{}\"\n",
            nix_shell_single_quote(filename),
            escape_nix_multiline(label)
        ));
    }
    s.push_str("                runHook postInstall\n");
    s.push_str("              '';\n");

    s.push_str("            }");
    s
}

// ---------- string/escaping helpers ----------

/// Render a Nix double-quoted string literal.
fn nix_string(s: &str) -> String {
    format!("\"{}\"", escape_nix_dq(s))
}

/// Escape a string for use inside a Nix double-quoted string.
fn escape_nix_dq(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '$' => out.push_str("\\$"),
            _ => out.push(c),
        }
    }
    out
}

/// Escape a line for inclusion inside a Nix `''...''` (indented) string.
///
/// In indented strings, the escape for `''` is `'''` and for `$` is `''$`. We
/// preserve `$` for shell variable use (the user command relies on `$out`,
/// `$GRANIT_DEPENDENCIES`, etc.), so we only need to protect literal `''` and
/// `${` sequences that Nix would otherwise interpolate.
fn escape_nix_multiline(line: &str) -> String {
    // Escape `${` (Nix interpolation) as `''${` so it reaches the shell literally,
    // and escape `''` as `'''`.
    let mut out = String::with_capacity(line.len());
    let bytes: Vec<char> = line.chars().collect();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == '\'' && i + 1 < bytes.len() && bytes[i + 1] == '\'' {
            out.push_str("'''");
            i += 2;
            continue;
        }
        if bytes[i] == '$' && i + 1 < bytes.len() && bytes[i + 1] == '{' {
            out.push_str("''${");
            i += 2;
            continue;
        }
        out.push(bytes[i]);
        i += 1;
    }
    out
}

/// Quote a filename as a single-quoted shell token (for use inside the `''`
/// build script). Single quotes are safe against all shell metacharacters.
fn nix_shell_single_quote(s: &str) -> String {
    // Within a Nix '' string, a single-quote is literal. Close/escape embedded
    // single quotes the shell way: ' -> '\''.
    let escaped = s.replace('\'', "'\\''");
    format!("'{escaped}'")
}

/// Render an attribute name, quoting if it isn't a bare Nix identifier.
fn nix_attr(name: &str) -> String {
    let is_bare = !name.is_empty()
        && name
            .chars()
            .enumerate()
            .all(|(i, c)| c.is_ascii_alphanumeric() || c == '_' || c == '-' || (i > 0 && c == '\''));
    let first_ok = name
        .chars()
        .next()
        .map(|c| c.is_ascii_alphabetic() || c == '_')
        .unwrap_or(false);
    if is_bare && first_ok {
        name.to_string()
    } else {
        nix_string(name)
    }
}

fn systems_list() -> String {
    SYSTEMS
        .iter()
        .map(|s| format!("\"{s}\""))
        .collect::<Vec<_>>()
        .join(" ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph;
    use crate::lock::{Lock, LockedInput};
    use crate::workspace::{DependencyRef, Package, Workspace};
    use std::collections::BTreeMap;
    use std::path::PathBuf;

    fn pkg(
        name: &str,
        tools: &[&str],
        deps: &[(&str, &str)],
        outputs: &[(&str, &str)],
        build: &str,
    ) -> Package {
        let mut cmds = BTreeMap::new();
        cmds.insert("build".to_string(), build.to_string());
        Package {
            name: name.to_string(),
            dir: PathBuf::from(name),
            tools: tools.iter().map(|s| s.to_string()).collect(),
            dependencies: deps
                .iter()
                .map(|(p, l)| DependencyRef {
                    package: p.to_string(),
                    label: l.to_string(),
                })
                .collect(),
            outputs: outputs
                .iter()
                .map(|(l, f)| (l.to_string(), f.to_string()))
                .collect(),
            commands: cmds,
        }
    }

    fn two_package_ws() -> Workspace {
        Workspace {
            name: "example".into(),
            root: PathBuf::from("/tmp/example"),
            nixpkgs_ref: "github:NixOS/nixpkgs/nixpkgs-unstable".into(),
            overlays: vec![],
            packages: vec![
                pkg(
                    "a",
                    &["coreutils"],
                    &[],
                    &[("hello", "hello.txt")],
                    "echo 'hello world' > hello.txt",
                ),
                pkg(
                    "b",
                    &["coreutils"],
                    &[("a", "hello")],
                    &[("result", "from-a.txt")],
                    "cat $GRANIT_DEPENDENCIES/a/hello > from-a.txt",
                ),
            ],
        }
    }

    fn lock_for(nixpkgs_rev: &str, overlays: Vec<LockedInput>) -> Lock {
        Lock {
            version: Lock::CURRENT_VERSION,
            nixpkgs: LockedInput {
                original_ref: "github:NixOS/nixpkgs/nixpkgs-unstable".into(),
                locked_ref: format!("github:NixOS/nixpkgs/{nixpkgs_rev}"),
                rev: Some(nixpkgs_rev.into()),
                nar_hash: Some("sha256-x=".into()),
                last_modified: Some(1),
            },
            overlays,
        }
    }

    #[test]
    fn generates_pinned_nixpkgs_input() {
        let ws = two_package_ws();
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("deadbeefdeadbeef", vec![]);
        let nix = generate(&ws, &g, &lock, "build").unwrap();
        assert!(
            nix.contains("nixpkgs.url = \"github:NixOS/nixpkgs/deadbeefdeadbeef\""),
            "missing pinned nixpkgs input:\n{nix}"
        );
    }

    #[test]
    fn generates_buildinputs_from_tools() {
        let ws = two_package_ws();
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);
        let nix = generate(&ws, &g, &lock, "build").unwrap();
        assert!(
            nix.contains("buildInputs = [ final.coreutils ];"),
            "missing buildInputs:\n{nix}"
        );
    }

    #[test]
    fn wires_dependency_outputs() {
        let ws = two_package_ws();
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);
        let nix = generate(&ws, &g, &lock, "build").unwrap();
        // b's derivation references a's store path via the overlay fixpoint.
        assert!(
            nix.contains("\"a:hello:${gp.a}\""),
            "missing dependency wiring:\n{nix}"
        );
        // The build script populates $GRANIT_DEPENDENCIES.
        assert!(nix.contains("$GRANIT_DEPENDENCIES/$depPkg/$depLabel"));
        // Shell parameter expansions in the boilerplate must be escaped so Nix
        // does not try to interpolate them.
        assert!(
            nix.contains("''${entry%%:*}"),
            "boilerplate shell expansion not escaped:\n{nix}"
        );
    }

    #[test]
    fn collects_declared_outputs() {
        let ws = two_package_ws();
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);
        let nix = generate(&ws, &g, &lock, "build").unwrap();
        // a collects hello.txt -> $out/hello
        assert!(
            nix.contains("cp -rL 'hello.txt' \"$out/hello\""),
            "missing output collection for a:\n{nix}"
        );
        // b collects from-a.txt -> $out/result
        assert!(nix.contains("cp -rL 'from-a.txt' \"$out/result\""));
    }

    #[test]
    fn composes_user_overlays_in_order() {
        let mut ws = two_package_ws();
        ws.overlays = vec![
            crate::workspace::Overlay {
                source: "github:acme/first".into(),
            },
            crate::workspace::Overlay {
                source: "github:acme/second".into(),
            },
        ];
        let g = graph::build(&ws).unwrap();
        let lock = lock_for(
            "rev",
            vec![
                LockedInput {
                    original_ref: "github:acme/first".into(),
                    locked_ref: "github:acme/first/1111".into(),
                    rev: Some("1111".into()),
                    nar_hash: None,
                    last_modified: None,
                },
                LockedInput {
                    original_ref: "github:acme/second".into(),
                    locked_ref: "github:acme/second/2222".into(),
                    rev: Some("2222".into()),
                    nar_hash: None,
                    last_modified: None,
                },
            ],
        );
        let nix = generate(&ws, &g, &lock, "build").unwrap();
        assert!(nix.contains("granitOverlay0.url = \"github:acme/first/1111\""));
        assert!(nix.contains("granitOverlay1.url = \"github:acme/second/2222\""));
        // Overlay 0 must appear before overlay 1 in the composed list.
        let idx0 = nix.find("granitOverlay0.overlays.default").unwrap();
        let idx1 = nix.find("granitOverlay1.overlays.default").unwrap();
        assert!(idx0 < idx1, "overlays not composed in declared order");
        // workspaceOverlay is applied after user overlays.
        assert!(nix.contains("userOverlays ++ [ workspaceOverlay ]"));
    }

    #[test]
    fn escapes_interpolation_in_user_commands() {
        // A user command containing `${FOO}` must reach the shell literally,
        // not be interpolated by Nix.
        let ws = Workspace {
            name: "x".into(),
            root: PathBuf::from("/tmp/x"),
            nixpkgs_ref: "github:NixOS/nixpkgs/nixpkgs-unstable".into(),
            overlays: vec![],
            packages: vec![pkg(
                "a",
                &[],
                &[],
                &[("o", "o.txt")],
                "echo ${HOME} > o.txt",
            )],
        };
        let g = graph::build(&ws).unwrap();
        let lock = lock_for("rev", vec![]);
        let nix = generate(&ws, &g, &lock, "build").unwrap();
        assert!(
            nix.contains("echo ''${HOME} > o.txt"),
            "interpolation not escaped:\n{nix}"
        );
    }
}
